---
- name: install mysql
  apt: name={{ item }} state=present
  with_items:
    - mariadb-server
    - python-mysqldb

- name: Create mysql database
  mysql_db: name={{ db_name }} state=present

- name: Create mysql user
  mysql_user: 
    name={{ db_user }} 
    password={{ db_password }} 
    priv=*.*:ALL